/** OKF-inspired Schema Field definition for trace data */
export type FieldType =
  | "string"
  | "integer"
  | "float"
  | "boolean"
  | "enum"
  | "json_schema"
  | "uuid"
  | "timestamp";

export interface SchemaField {
  id: string;
  name: string;
  type: FieldType;
  description: string;
  required: boolean;
  /** For numeric types */
  min?: number;
  max?: number;
  alert_threshold?: number;
  unit?: string; // e.g. "ms", "tokens", "USD"
  /** For enum type */
  enum_values?: string[];
  /** For json_schema type — reference to an external schema */
  schema_ref?: string;
  /** Example value for documentation */
  example?: string;
  created_at: number;
  updated_at: number;
}

export interface SchemaExport {
  format: "okf/trace/v1";
  schema_version: string;
  name: string;
  description: string;
  exported_at: number;
  fields: Omit<SchemaField, "id" | "created_at" | "updated_at">[];
}

/** Pre-built reference fields that users can import as a starting point */
export const DEFAULT_TRACE_FIELDS: Omit<SchemaField, "id" | "created_at" | "updated_at">[] = [
  { name: "trace_id", type: "uuid", description: "Unique identifier for the trace", required: true, example: "abc-123-def-456" },
  { name: "model_name", type: "string", description: "The LLM model used for this trace", required: true, example: "GPT-4o" },
  { name: "model_provider", type: "enum", description: "The provider of the model", required: false, enum_values: ["openai", "anthropic", "google", "meta", "mistral", "cohere"], example: "openai" },
  { name: "user_query", type: "string", description: "The input prompt or query sent by the user", required: true, example: "What's my account balance?" },
  { name: "response", type: "string", description: "The output generated by the model", required: false, example: "Your balance is $1,200." },
  { name: "latency_ms", type: "integer", description: "End-to-end response time in milliseconds", required: true, min: 0, max: 120000, alert_threshold: 5000, unit: "ms", example: "1423" },
  { name: "prompt_tokens", type: "integer", description: "Number of tokens in the input prompt", required: true, min: 0, max: 128000, alert_threshold: 64000, unit: "tokens", example: "245" },
  { name: "completion_tokens", type: "integer", description: "Number of tokens in the model response", required: true, min: 0, max: 16384, alert_threshold: 4096, unit: "tokens", example: "89" },
  { name: "cost_usd", type: "float", description: "Cost of the trace in USD", required: true, min: 0, max: 100, alert_threshold: 0.05, unit: "USD", example: "0.0023" },
  { name: "status", type: "enum", description: "Execution status of the trace", required: true, enum_values: ["success", "error", "partial"], example: "success" },
  { name: "environment", type: "enum", description: "Deployment environment", required: false, enum_values: ["production", "staging", "development", "test"], example: "production" },
  { name: "injection_flagged", type: "boolean", description: "Whether prompt injection was detected", required: false, example: "false" },
  { name: "injection_severity", type: "enum", description: "Severity of detected prompt injection", required: false, enum_values: ["none", "low", "medium", "high", "critical"], example: "none" },
  { name: "response_json", type: "json_schema", description: "Structured output as JSON", required: false, schema_ref: "my_output_schema_v1", example: '{"status": "success"}' },
  { name: "created_at", type: "timestamp", description: "When the trace was created", required: true, example: "2025-07-01T12:00:00Z" },
];